### ISSUE TITLE
Issue with Natural package

### ISSUE THREAD

**Issue by dsottimano** [sjhorn/node-simhash#1]
Any ideas here? 

TypeError: logger.setLevel is not a function
    at Object.<anonymous> (D:\source\simhash\node_modules\natural\lib\natural\brill_pos_tagger\lib\Brill_POS_Tagger.js:26:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\source\simhash\node_modules\natural\lib\natural\index.js:81:26)
    at Module._compile (module.js:571:32)

**Comment by akrylysov** [comment]
@dsottimano I found a workaround, you need to install log4js version 1.1.1:

```
npm install log4js@1.1.1
```
The new version of log4js doesn't have `logger.setLevel` anymore.

**Comment by roast123** [comment]
i tried what your said ,but it does not work.
